# Generated by Django 4.1.7 on 2023-03-26 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=120)),
                ('post_code', models.CharField(blank=True, max_length=6)),
                ('amts_code', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_department', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('landline', models.CharField(max_length=20)),
                ('mob_phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_ministry', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_organisation', models.CharField(max_length=90)),
                ('additional_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone_directory_app.additionalinfo')),
                ('general_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone_directory_app.organisation')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_directory_app.ministry')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentInOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_directory_app.department')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_directory_app.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisations', models.ManyToManyField(blank=True, to='phone_directory_app.organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInOrganisationDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phone_directory_app.employee')),
                ('organisation_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phone_directory_app.departmentinorganisation')),
            ],
            options={
                'unique_together': {('employee', 'organisation_department')},
            },
        ),
    ]
