# Generated by Django 4.1.7 on 2023-03-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_directory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinorganisationdepartment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_directory_app.employee'),
        ),
        migrations.AlterField(
            model_name='employeeinorganisationdepartment',
            name='organisation_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_directory_app.departmentinorganisation'),
        ),
    ]
